#Postgres
postgres:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: postgres
    url: 'jdbc:postgresql://localhost:5432/loja'
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
      
#Mysql
spring:
  datasource:
    password: admin
    username: root
    url: 'jdbc:mysql://mysql_loja:3306/loja'
  jpa:
    hibernate:
      ddl-auto: update
      generate-ddl: true
      show-sql: true
  
      




