postgres:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: postgres
    url: 'jdbc:postgresql://localhost:5432/loja'
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update

server.port=${port:1980}
spring:
  datasource:
    password: admin
    username: root
    url: 'jdbc:mysql://${MYSQL_HOST:localhost}:3306/loja'
  jpa:
    hibernate:
      ddl-auto: update

